data:
  img_size: ${common.img_size}
  batch_size: ${common.batch_size}
  default_pad_value: 0
  max_detection: ${nms.max_detection}
  seed: ${common.seed}
  mask_ratio: 4
  cache: false
  mosaic: true
  transforms:
    random_crop:
      min_crop_ratio: 0.2
      max_crop_ratio: 0.9
      prob: 0.5
      seed: ${data.seed}

    random_hsvc:
      v_max_delta: 0.2
      h_max_delta: 0.2
      s_min: 0
      s_max: 2
      c_min: 0
      c_max: 2

    # random_blur:
    #   kernel_size: [3, 3]
    #   min_sigma: 0
    #   max_sigma: 10

  batched_transform:
    random_flip_vertical:
      seed: ${data.seed}
      prob: 0.5

    random_flip_horizontal:
      seed: ${data.seed}
      prob: 0.5